= sql-parser

sql-parser is parser substantially copy-and-paste from the book <flex & biosn>

 - generates Reverse Polish Notation (RPN) of SQL statements
 - integrates with GO's yacc and nex instead of Flex & BISON

I wrote this code to get acquainted with GO and SQL for further develop purpose. This is a subset of SQL. The ultimate definitions for SQL are the standards documents published by ANSI and
ISO including ISO/IEC 9075-2:2003, which defines SQL, and a variety of related documents
that define the way to embed SQL in other programming languages and in XML.

== Installation ==

Get nex tool:

  $go get github.com/blynn/nex
  $cd github.com/blynn/nex
  $go build
  $ln -s nex /usr/bin/nex

Get sql-parser 

  $go get github.com/soforth/sql-parser
  $cd github.com/soforth/sql-parser

Run:

  $make
  $./sql-parser < sql

== Example ==

  $cat sql
  insert into `t1` select * from t2 where t2.c > 100;
  $./sql-parser < sql
  SELECTALL
  TABLE t2
  FIELDNAME t2.c
  NUMBER 100
  CMP 2
  WHERE
  SELECT 0 1 1
  INSERTSELECT 0 t
  STMT
  
== LICENSE ==

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

